FROM paasim/stack-arm as build

RUN git clone https://github.com/paasim/timer.git \
  && cd timer \
  && stack install --resolver lts-11.22

FROM scratch

COPY --from=build /root/.local/bin/timer-exe /timer

ENTRYPOINT ["./timer"]

